server:
  port: 0
spring:
  zipkin: http://127.0.0.1:9411/
  datasource:
    url: jdbc:mysql://localhost:3306/quote-service
    username: root
    password: watashiwa
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  application:
    name: quote-service

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

